-- -------------------------
-- Tables
-- -------------------------
CREATE TABLE IF NOT EXISTS majors (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code CITEXT UNIQUE NOT NULL,
    name TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);