services:

  - type: web
    name: api
    runtime: node
    rootDir: server
    plan: free
    region: oregon
    buildCommand: npm ci && npm run build --if-present                        
    preDeployCommand: npm run db:setup:render
    startCommand: npm run start
    healthCheckPath: /healthz
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: kanvas-db
          property: connectionString
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: JWT_SECRET
        sync: false
      - key: JWT_EXPIRES
        value: 7d
      - key: CORS_ORIGIN
        value: https://kanvas-app.onrender.com
    healthCheckPath: /api/auth/me

databases:
  - name: kanvas-db
    databaseName: kanvas
    user: kanvas_user
    plan: free
    region: oregon
    ipAllowList: []
    postgresMajorVersion: "16"

version: "1"
