services:
  - type: web
    name: kanvas-app
    runtime: node
    repo: https://github.com/amilia-n/Kanvas
    buildCommand: |
      cd server && npm ci
      cd ../client && npm ci && npm run build
    startCommand: cd server && node server.js
    plan: free
    region: oregon
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: kanvas-db
          property: connectionString
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: JWT_SECRET
        sync: false
      - key: JWT_EXPIRES
        value: 7d
      - key: CORS_ORIGIN
        value: https://kanvas-app.onrender.com
    healthCheckPath: /healthz

databases:
  - name: kanvas-db
    databaseName: kanvas
    user: kanvas_user
    plan: free
    region: oregon
    ipAllowList: []
    postgresMajorVersion: "16"

version: "1"