services:
  test-db:
    image: postgres:16-alpine
    container_name: kanvas-test-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: testpassword
      POSTGRES_DB: kanvas_test
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d kanvas_test"]
      interval: 2s
      timeout: 3s
      retries: 15
    tmpfs:
      - /var/lib/postgresql/data

  test-runner:
    build:
      context: .
      dockerfile: Dockerfile.test
    container_name: kanvas-test-runner
    environment:
      NODE_ENV: test
      DATABASE_URL: postgres://postgres:testpassword@test-db:5432/kanvas_test
      JWT_SECRET: test_jwt_secret
      JWT_EXPIRES: 1h
    depends_on:
      test-db:
        condition: service_healthy
    volumes:
      - .:/app
      - /app/node_modules
    working_dir: /app
    command: ["npm", "run", "test:run"]